# Backend image: multi-stage build. Stage 1 trains the model at BUILD
# time (using the full training dependency set); stage 2 is the lean
# runtime image that only gets the trained artifacts copied in, not
# the training dependencies themselves. This makes the final image
# fully self-contained -- no shared volume, no deploy-time training
# hook, no dependency ordering between services. Works identically on
# plain `docker build`, docker-compose, and every cloud platform in
# deploy/ (Render, Railway, AWS, Azure, GCP).

# ---- Stage 1: train ----
FROM python:3.11-slim AS trainer

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-train.txt .
RUN pip install --no-cache-dir -r requirements-train.txt

COPY src/ ./src/
COPY data/ ./data/

# --no-promote: this is a build-time training run inside an isolated
# image, not a governed release -- MLflow registry promotion (see
# src/train.py) is a separate, deliberate step run against the shared
# MLflow tracking server, not something that should happen implicitly
# on every image build.
RUN python -m src.train --no-promote

# ---- Stage 2: runtime ----
FROM python:3.11-slim

WORKDIR /app

COPY requirements-backend.txt .
RUN pip install --no-cache-dir -r requirements-backend.txt

COPY src/ ./src/
COPY backend/ ./backend/

# Trained artifacts from stage 1, plus the static reference data
# (Phase 4/5/8/9 study results) that isn't generated by training at all.
COPY --from=trainer /app/models/churn_model.pkl ./models/churn_model.pkl
COPY --from=trainer /app/models/preprocessor.pkl ./models/preprocessor.pkl
COPY --from=trainer /app/models/feature_columns.json ./models/feature_columns.json
COPY --from=trainer /app/models/metrics.json ./models/metrics.json
COPY models/model_comparison.json models/business_findings.json ./models/

RUN useradd --create-home appuser
USER appuser

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()" || exit 1

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
